# Generated by Django 4.2.5 on 2023-09-14 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_items_delivered', models.IntegerField(default=0)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delivered Item',
                'verbose_name_plural': 'Delivered Items',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('bike', 'Bike'), ('motorcycle', 'Motorcycle'), ('car', 'Car')], max_length=50)),
            ],
            options={
                'verbose_name': 'Delivery Method',
                'verbose_name_plural': 'Delivery Methods',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('drivers license', 'Drivers License'), ('national id', 'National ID'), ('biometric Residence Permit', 'Biometric Residence Permit')], max_length=50)),
                ('document', models.ImageField(blank=True, null=True, upload_to='delivery_person_documents')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, max_length=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Delivery Person',
                'verbose_name_plural': 'Delivery People',
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_enroute', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deliver_personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliveryperson')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverymethod')),
            ],
            options={
                'verbose_name': 'Delivery Status',
                'verbose_name_plural': 'Delivery Statuses',
            },
        ),
    ]
